version: "3"
services:
  api:
    image: code0ex/api_reverse_proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - api

networks:
  api:
    driver: bridge
