version: "3.8"
services:
  ssh:
    image: code0ex/ssh_reverse_proxy:prod
    container_name: ssh_reverse_proxy
    hostname: ssh_reverse_proxy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ssh_reverse_proxy
      platforms:
        - linux/arm64
        - linux/amd64
    networks:
      - api
    ports:
      - "2222:22"

  db:
    image: postgres:13
    container_name: db
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - api
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_push:
    image: code0ex/db_push_reverse_proxy:prod
    container_name: db_push
    hostname: db_push
    build:
      context: .
      dockerfile: Dockerfile
      target: db_push_reverse_proxy
      platforms:
        - linux/arm64
        - linux/amd64
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - api
    depends_on:
      - db

  api:
    image: code0ex/api_reverse_proxy:prod
    container_name: api
    hostname: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: api_reverse_proxy
      platforms:
        - linux/arm64
        - linux/amd64
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DOMAIN_NAME=${PROD_DOMAIN_NAME}
    networks:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${PROD_DOMAIN_NAME}`)"
      - "traefik.http.routers.api.entrypoints=websecure,web"
      - "traefik.http.services.api.loadbalancer.server.port=8081"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
    depends_on:
      - ssh
      - db_push
      - db

  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    hostname: "traefik"
    restart: "always"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.udp.address=:9090/udp"
      - "--entrypoints.tcp.address=:9090/tcp"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--providers.http.endpoint=https://api.${PROD_DOMAIN_NAME}/api/traefik"
      - "--providers.http.pollInterval=5s"
      - "--providers.http.pollTimeout=30s"
      ## Uncomment the following line to use the staging server
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      ## Uncomment the following line to use the production server
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=louis.sasse@protonmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "9090:9090/udp"
      - "9090:9090/tcp"
    networks:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${PROD_DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure,web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
    depends_on:
      - api

networks:
  api:
    driver: bridge

volumes:
  db-data:
    driver: local
