name: ci

on:
  release:
    types: [published]
    branches:
      - $default-branch

  # temporary
  push:
    branches:
      - "*"

env:
  IMAGE_NAMES: |
    code0ex/api_reverse_proxy
    code0ex/db_push_reverse_proxy
    code0ex/ssh_reverse_proxy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        id: build
        run: |
          for image in $IMAGE_NAMES; do
            docker buildx build --push --platform ${{ matrix.platform }} \
              --label "org.opencontainers.image.source=${{ github.repository }}" \
              --label "org.opencontainers.image.version=${{ steps.meta.outputs.version }}" \
              --tag $image:${{ steps.meta.outputs.version }} \
              .
            echo "DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $image:${{ steps.meta.outputs.version }})" >> $GITHUB_ENV
            mkdir -p /tmp/digests
            touch "/tmp/digests/${DIGEST#sha256:}"
          done

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest lists
        run: |
          for image in $IMAGE_NAMES; do
            docker buildx imagetools create \
              --tag $image:${{ steps.meta.outputs.version }} \
              $(find /tmp/digests -name '*.json' -exec jq -r '.manifests[].digest' {} +)
          done

      - name: Inspect images
        run: |
          for image in $IMAGE_NAMES; do
            docker buildx imagetools inspect $image:${{ steps.meta.outputs.version }}
          done
